# Теория вероятностей

In [273]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import math
from scipy import stats
import statistics

plt.style.use('seaborn-whitegrid')
%config InlineBackend.figure_formats = ['svg']

In [274]:
def statistic(samples: np.ndarray) -> float:
    return (samples.mean() - 1) / (samples.std(ddof=1) / np.sqrt(samples.shape[0]))

## Домашнее задание 6

**Задача 1**

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.


**Решение**

In [275]:
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

In [276]:
df = pd.DataFrame()
df['zp'] = zp
df['ks'] = ks

df.head()

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459

In [277]:
#ковариация расчет

X = df['zp']
Y = df['ks']

MX = X.mean()
MY = Y.mean()

cov = ((X - MX) * (Y - MY)).sum() / (X.shape[0] - 1)
cov

10175.37777777778

In [278]:
#ковариация np

np.cov(X, Y, ddof=1)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [279]:
#коэффициент корреляции Пирсона расчет

corr = cov / (X.std() * Y.std())
corr

0.8874900920739164

In [280]:
#коэффициент корреляции Пирсона np

np.corrcoef(X, Y)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [281]:
#коэффициент корреляции Пирсона pd

df[['zp', 'ks']].corr()

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

**Задача 2**

Измерены значения IQ выборки студентов,обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111.

Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.


In [289]:
iq = np.array[131, 125, 115, 122, 131, 115, 107, 99, 125, 111]

iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [292]:
n = iq.shape[0]

mean = iq.mean()
std = iq.std(ddof=1)

n, mean, std

(10, 118.1, 10.54566788359614)

In [294]:
p = 0.95
alpha = 1 - p

t1 = stats.norm.ppf(alpha / 2)
t2 = stats.norm.ppf(1 - alpha / 2)

t1, t2

(-1.959963984540054, 1.959963984540054)

In [295]:
# доверительный интервал

(mean + t1 * std / np.sqrt(n), mean + t2 * std / np.sqrt(n))

(111.56384743341334, 124.63615256658665)

**Задача 3**

Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.


**Решение**

In [296]:
sqr_sigma = 25
mean = 174.2
n = 27
p = 0.95

In [297]:
alpha = 1 - p

t1 = stats.norm.ppf(alpha / 2)
t2 = stats.norm.ppf(1 - alpha / 2)

t1, t2

(-1.959963984540054, 1.959963984540054)

In [299]:
# доверительный интервал

(mean + t1 * np.sqrt(sqr_sigma) / np.sqrt(n), mean + t2 * np.sqrt(sqr_sigma) / np.sqrt(n))

(172.3140237765397, 176.08597622346028)